import pygame
WINDOW_WIDTH = 400
WINDOW_HEIGHT = 600
TOP_LEFT_SQUARE_POS_X = 0
TOP_LEFT_SQUARE_POS_Y = 0
LEVEL_WIDTH = 280
LEVEL_HEIGHT = 280

YOU_WIN_WIDTH = 280
YOU_WIN_HEIGHT = 100

YOU_WIN_POS_X = (WINDOW_WIDTH - LEVEL_WIDTH) / 2
YOU_WIN_POS_Y =( (WINDOW_HEIGHT - LEVEL_HEIGHT) / 2 )-110

QUEENS_LOGO_POS_X = YOU_WIN_POS_X + 10
QUEENS_LOGO_POS_Y = YOU_WIN_POS_Y +50
QUEENS_LOGO_WIDTH = 250
QUEENS_LOGO_HEIGHT = 70
TIME_POS_X = (WINDOW_WIDTH - LEVEL_WIDTH) / 2
TIME_POS_Y = (WINDOW_HEIGHT - LEVEL_HEIGHT) / 2 + LEVEL_HEIGHT
LEVEL_POS_X = (WINDOW_WIDTH - LEVEL_WIDTH) / 2
LEVEL_POS_Y = (WINDOW_HEIGHT - LEVEL_HEIGHT) / 2
SQUARE_POS_X =( (WINDOW_WIDTH - LEVEL_WIDTH) / 2)
SQUARE_POS_Y = ( (WINDOW_HEIGHT - LEVEL_HEIGHT) / 2 )
SQUARE_WIDTH = 40
SQUARE_HEIGHT = 40
BLACK = (0, 0, 0)
WHITE = (255,255,255)

win_image = pygame.transform.scale(pygame.image.load("Pictures/you_win.jpg"), (YOU_WIN_WIDTH, YOU_WIN_HEIGHT))
queens_logo_img = pygame.transform.scale(pygame.image.load("Pictures/queens_logo_new.png"),
                                         (QUEENS_LOGO_WIDTH, QUEENS_LOGO_HEIGHT))
