WINDOW_WIDTH = 400
WINDOW_HEIGHT = 600
TOP_LEFT_SQUARE_POS_X = 0
TOP_LEFT_SQUARE_POS_Y = 0
LEVEL_WIDTH = 280
LEVEL_HEIGHT = 280

YOU_WIN_WIDTH = 280
YOU_WIN_HEIGHT = 100
YOU_WIN_POS_X = (WINDOW_WIDTH - LEVEL_WIDTH) / 2
YOU_WIN_POS_Y =( (WINDOW_HEIGHT - LEVEL_HEIGHT) / 2 )-110

LEVEL_POS_X = (WINDOW_WIDTH - LEVEL_WIDTH) / 2
LEVEL_POS_Y = (WINDOW_HEIGHT - LEVEL_HEIGHT) / 2
SQUARE_POS_X =( (WINDOW_WIDTH - LEVEL_WIDTH) / 2)
SQUARE_POS_Y = ( (WINDOW_HEIGHT - LEVEL_HEIGHT) / 2 )
SQUARE_WIDTH = 40
SQUARE_HEIGHT = 40
BLACK = (0, 0, 0)
GREY = (50, 50, 50)
WHITE = (255, 255, 255)
LIGHT_GRAY = (134, 134, 134)
